version: '3.4'

services:
  alpha:
    image: ${DOCKER_REGISTRY-}alpha
    build:
      context: .
      dockerfile: Alpha/Dockerfile
    networks:
      - peers

networks:
   peers:
      driver: bridge